environment:
  name: prod
  project: cdf-bootcamp-59-prod
  type: prod
  selected:
  - modules/
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: ${CDF_PROJECT} 
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR TEST/PROD DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: 883e1e5e-d568-4f43-956e-4a905d4bbe41
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: e259f12c-932a-4373-8912-6c9ffbed83db
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readonly_source_id: 24f8b921-86c5-415a-a1ed-f653794707fe
      # OBJECT ID FOR TEST/PROD ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: 01319990-bc16-4287-b119-2f1e96d7258b

      # data_developer_source_id: e7d1ed26-59c5-414d-8959-fc7fc2c7e749
      # data_extractor_source_id: 
      # data_pipeline_source_id: 2263f4fe-dc5e-40a8-ada6-c28af3e3c21c
      # api_ds_externalId: api_ice_cream_data
      

      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
          # oee_ds_externalId: oee_ice_cream_data

    
